apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-scout.fullname" . }}-config
  labels:
    {{- include "job-scout.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
