apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-scout.fullname" . }}
  labels:
    {{- include "job-scout.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "job-scout.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
